%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"
# Left Camera calibration and distortion parameters (Pinhole Model)
Camera.fx: 432.496042035043
Camera.fy: 432.496042035043
Camera.cx: 320.5
Camera.cy: 240.5
Camera.k1: 0.0
Camera.k2: 0.0
Camera.p1: 0.0
Camera.p2: 0.0
Camera.k3: 0.0



# Right Camera calibration and distortion parameters (Pinhole Model)
Camera2.fx: 432.496042035043
Camera2.fy: 432.496042035043
Camera2.cx: 320.5
Camera2.cy: 240.5
Camera2.k1: 0.0
Camera2.k2: 0.0
Camera2.p1: 0.0
Camera2.p2: 0.0
Camera2.k3: 0.0

Camera.width: 640
Camera.height: 480

# Stereo baseline multiplied by fx for depth estimation
# Adjust the baseline value according to the actual physical distance between the camera centers
Camera.bf: 30.7746024  # Example calculated as fx * baseline in meters (e.g., 432.496042035043 * 0.07m)

# Transformation matrix from the right camera to the left camera
# Assuming the baseline is the translation in meters on the x-axis
Tlr: !!opencv-matrix
  rows: 3
  cols: 4
  dt: f
  data: [1.0, 0.0, 0.0, 0.07,  # Adjusted to actual baseline translation of 0.07 meters
         0.0, 1.0, 0.0, 0.0,
         0.0, 0.0, 1.0, 0.0]

# Camera frames per second
Camera.fps: 30.0

# Color order of the images (0: BGR, 1: RGB)
Camera.RGB: 1

# Depth threshold (Close/Far)
ThDepth: 40.0
# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000 # Tested with 1250

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 15 # 20
ORBextractor.minThFAST: 7 # 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500